name: Token Cold Storage CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tests/js

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
      - run: npm ci
      - run: npm test
